# Le docker-compose est incomplet, un volume devrait être
# déclarer pour éviter la perte de donnée
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "cinema_db"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "55432:5432"
    container_name: cinema_db